# Generated by Django 5.1.1 on 2024-09-06 19:23

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_iconsocialweb_homepage_body_homepage_logo_aboutpage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nombre', models.CharField(max_length=255)),
                ('body', wagtail.fields.StreamField([('texto_imagen_arriba', 3), ('texto_imagen_abajo', 3), ('texto_imagen_derecha', 4), ('texto_imagen_izquierda', 3), ('texto_primario_y_secundario', 5), ('cita', 8), ('galeria', 12), ('video_embebido', 14), ('boton_mas_accion', 17), ('accordion', 22), ('caracteristica', 28), ('estadisticas', 33), ('documento', 38), ('pestannas', 42)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto primario', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Texto secundario', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('texto_primario', 1), ('texto_secundario', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('texto_primario', 1), ('texto_secundario', 2), ('image', 0)]], {}), 5: ('wagtail.blocks.StructBlock', [[('texto_primario', 1), ('texto_secundario', 2)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Autor', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Cita', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('author', 6), ('cita', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Galería de imágenes'}), 12: ('wagtail.blocks.StructBlock', [[('texto', 9), ('images', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL del video', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('texto_primario', 1), ('url', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto de la llamada a la acción', 'required': True}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL a la que se dirige', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('texto_primario', 15), ('url', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del acordeón', 'required': True}), 19: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Contenido del acordeón', 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('title', 18), ('content', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('items', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la característica', 'required': True}), 24: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción de la característica', 'required': True}), 25: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de la característica'}), 26: ('wagtail.blocks.StructBlock', [[('title', 23), ('description', 24), ('image', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('features', 27)]], {}), 29: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Número a mostrar', 'required': True}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'Etiqueta del contador', 'required': True}), 31: ('wagtail.blocks.StructBlock', [[('cantidad', 29), ('nombre', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {}), 33: ('wagtail.blocks.StructBlock', [[('contadores', 32)]], {}), 34: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nombre del documento', 'required': True}), 35: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Documento', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('nombre', 34), ('documento', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.StructBlock', [[('docs', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la pestaña', 'required': True}), 40: ('blocks.models.SimpleTextBlock', (), {}), 41: ('wagtail.blocks.StreamBlock', [[('texto_imagen_arriba', 3), ('texto_imagen_abajo', 3), ('texto_simple', 40), ('texto_imagen_derecha', 4), ('texto_imagen_izquierda', 3), ('texto_primario_y_secundario', 5), ('cita', 8), ('galeria', 12), ('video_embebido', 14), ('boton_mas_accion', 17), ('accordion', 22), ('caracteristica', 28), ('contador', 33)]], {'label': 'Contenido de la pestaña'}), 42: ('wagtail.blocks.StructBlock', [[('title', 39), ('content', 41)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'Página personalizada',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EstadisticaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'stats_items',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Preguntas Frecuentes',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GaleriaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Página de Galería',
                'verbose_name_plural': 'Páginas de Galería',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contenido_extra',
            field=wagtail.fields.StreamField([('texto_imagen_arriba', 3), ('texto_imagen_abajo', 3), ('texto_imagen_derecha', 4), ('texto_imagen_izquierda', 3), ('texto_primario_y_secundario', 5), ('cita', 8), ('galeria', 12), ('video_embebido', 14), ('boton_mas_accion', 17), ('accordion', 22), ('caracteristica', 28), ('estadisticas', 33), ('documento', 38), ('pestanna', 42)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto primario', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Texto secundario', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('texto_primario', 1), ('texto_secundario', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('texto_primario', 1), ('texto_secundario', 2), ('image', 0)]], {}), 5: ('wagtail.blocks.StructBlock', [[('texto_primario', 1), ('texto_secundario', 2)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Autor', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Cita', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('author', 6), ('cita', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Galería de imágenes'}), 12: ('wagtail.blocks.StructBlock', [[('texto', 9), ('images', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL del video', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('texto_primario', 1), ('url', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto de la llamada a la acción', 'required': True}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL a la que se dirige', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('texto_primario', 15), ('url', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del acordeón', 'required': True}), 19: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Contenido del acordeón', 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('title', 18), ('content', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('items', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la característica', 'required': True}), 24: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción de la característica', 'required': True}), 25: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de la característica'}), 26: ('wagtail.blocks.StructBlock', [[('title', 23), ('description', 24), ('image', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('features', 27)]], {}), 29: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Número a mostrar', 'required': True}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'Etiqueta del contador', 'required': True}), 31: ('wagtail.blocks.StructBlock', [[('cantidad', 29), ('nombre', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {}), 33: ('wagtail.blocks.StructBlock', [[('contadores', 32)]], {}), 34: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nombre del documento', 'required': True}), 35: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Documento', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('nombre', 34), ('documento', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.StructBlock', [[('docs', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la pestaña', 'required': True}), 40: ('blocks.models.SimpleTextBlock', (), {}), 41: ('wagtail.blocks.StreamBlock', [[('texto_imagen_arriba', 3), ('texto_imagen_abajo', 3), ('texto_simple', 40), ('texto_imagen_derecha', 4), ('texto_imagen_izquierda', 3), ('texto_primario_y_secundario', 5), ('cita', 8), ('galeria', 12), ('video_embebido', 14), ('boton_mas_accion', 17), ('accordion', 22), ('caracteristica', 28), ('contador', 33)]], {'label': 'Contenido de la pestaña'}), 42: ('wagtail.blocks.StructBlock', [[('title', 39), ('content', 41)]], {})}, null=True),
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_items', to='home.estadisticapage')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='home.faqpage')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoriagaleria', verbose_name='Categoría de la Categoría')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagen Galería')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_items', to='home.galeriapage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('url', models.URLField(blank=True, verbose_name='URL del Partner')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
            ],
        ),
    ]
