# Generated by Django 5.1.1 on 2024-09-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aboutpage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='imagen',
            new_name='image',
        ),
    ]
